name: blackx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ta-lib
  - akshare>=1.10.0
  - backtrader>=1.9.78.123
  - pandas-ta>=0.3.14b0
  - pandas>=1.5.0
  - numpy>=1.21.0
  - plotly>=5.13.0
  - fastapi>=0.95.0
  - uvicorn>=0.22.0
  - streamlit>=1.22.0
  - sqlalchemy>=2.0.0
  - apscheduler>=3.10.0
  - python-dotenv>=1.0.0
  - requests>=2.28.0
  - pytest>=7.3.1 