# 策略配置文件模板
strategies:
  # 策略1：双均线策略
  ma_crossover:
    name: "双均线交叉策略"
    description: "使用快慢均线交叉作为交易信号"
    parameters:
      fast_period: 5
      slow_period: 20
    indicators:
      - name: "SMA"
        code: |
          data['fast_ma'] = data['close'].rolling(window=params['fast_period']).mean()
          data['slow_ma'] = data['close'].rolling(window=params['slow_period']).mean()
        params:
          fast_period: 5
          slow_period: 20
    signals:
      buy:
        code: "data['fast_ma'] > data['slow_ma']"
      sell:
        code: "data['fast_ma'] < data['slow_ma']"
    position_sizing:
      type: "fixed"
      value: 0.1

  # 策略2：RSI策略
  rsi_strategy:
    name: "RSI超买超卖策略"
    description: "使用RSI指标判断超买超卖"
    parameters:
      rsi_period: 14
      overbought: 70
      oversold: 30
    indicators:
      - name: "RSI"
        code: |
          delta = data['close'].diff()
          gain = (delta.where(delta > 0, 0)).rolling(window=params['rsi_period']).mean()
          loss = (-delta.where(delta < 0, 0)).rolling(window=params['rsi_period']).mean()
          rs = gain / loss
          data['rsi'] = 100 - (100 / (1 + rs))
        params:
          rsi_period: 14
    signals:
      buy:
        code: "data['rsi'] < params['oversold']"
      sell:
        code: "data['rsi'] > params['overbought']"
    position_sizing:
      type: "fixed"
      value: 0.1

  # 策略3：布林带策略
  bollinger_bands:
    name: "布林带策略"
    description: "使用布林带判断价格突破"
    parameters:
      period: 20
      std_dev: 2
    indicators:
      - name: "BB"
        code: |
          data['middle_band'] = data['close'].rolling(window=params['period']).mean()
          std = data['close'].rolling(window=params['period']).std()
          data['upper_band'] = data['middle_band'] + std * params['std_dev']
          data['lower_band'] = data['middle_band'] - std * params['std_dev']
        params:
          period: 20
          std_dev: 2
    signals:
      buy:
        code: "data['close'] < data['lower_band']"
      sell:
        code: "data['close'] > data['upper_band']"
    position_sizing:
      type: "fixed"
      value: 0.1

# 策略组合配置
strategy_portfolio:
  name: "组合策略"
  strategies:
    - name: "ma_crossover"
      weight: 0.4
    - name: "rsi_strategy"
      weight: 0.3
    - name: "bollinger_bands"
      weight: 0.3
  rebalance_period: "1M" 